### PR TITLE
Gwent-data PHP Card Generator

### PR DESCRIPTION
**Pull request by Meowcate**
Adding the content of the PHP card generator, using the gwent-data JSON file.

Include the composer file and the assets, with the exception of the artworks (shouldn't be stored on Github).

### CODE REVIEW

**Comment by Meowcate** [comment]
Ok, be cool with this, this is my first PR.
Usually I use git at work with Bitbucket, I never contributed on github so far.

The script isn't perfect yet, maybe we should wait to make a Python version, your choice.

Possible TODO : 

- adding another step with the Imagick work so one can use directly the game artworks (actually you need to crop the image to remove the transparent part : for performance reasons, each card is on a 2^X px square image). So far I was doing this beforehand using bash.
- adding a 4K argument. The artworks are resized bigger because the **original** size is bigger than the images from **high.standard** file. But I'm not sure it's really that important.
- full card generator : like it works on my website, using arguments so you can build any card you want by passing strength, faction, and card filename, so you can create custom cards like custom-gwent does.

**Comment by jamieadkins95** [comment]
Amazing work, thanks!

Having seen how large this PR is, I've changed my mind and I am leaning towards putting this in it's own repository again. 

Will wait on @Zolmeister and @Tri125 opinions, but since this will be maintained separately from the main data set, and issues/bugs will be separate, I think it is sensible to let this live in it's own repo.

**Comment by Tri125** [comment]
I'm in favor of a different repo. We could accept the PR here for convenience then move it out.

**Comment by Zolmeister** [comment]
These asset files, how are they generated? Can they be extracted via script as well?

I'm in favor of a single repo that handles all tasks related to the games raw data files.
Until the project gets larger, separating into another repo feels superfluous

**Comment by Zolmeister** [comment]
Can you add build/run instructions to the readme?

**Comment by Meowcate** [comment]
The assets files can't be generated : I created it myself (and it tooks hours and hours, especially the banners). Gwent cards' elements are 3D, I took the 2D textures and created a 2D version of what the meshes look like.
(If you don't like binary, we can still create big base64 datas to generate the files. Not cute, but it's a solution. We can also regroup the assets folder into an archive, as it wouldn't change much in the future)

Remember, the artworks have to be extracted using Unity Asset Extractor. So the use of a 3rd tool party is still needed.

I'll add instructions about the installation on the readme. My bad : seeing the composer.json file, PHP devs usually know how it works.

**Comment by jamieadkins95** [comment]
If we need to include assets from the game then we should definitely put this all in a new repository that has a non commercial license

**Comment by Tri125** [comment]
Aye jamie, and if a DMCA is thrown in our general direction (probably won't happen) it won't take down gwent-data with it. The two tools cover different goals too so for me it makes sense to keep them separated.

@Meowcate I imagine your comment about base64 is because I mentioned that git doesn't play good with binary? It's fine, leave them how they are. It would just give a different representation of the same underlying data without changing much.

**Comment by jamieadkins95** [comment]
This project has it's own [repository](https://github.com/GwentCommunityDevelopers/card-images). Closing.

**Pull request closed without merging**
